#!/usr/bin/env bash
# =============================================================================
# Embedded Cross-Compile Doctor - fix.sh
# Auto-fix common issues found by diagnose.sh
# =============================================================================
set -uo pipefail

VERSION="1.0.0"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'

SRC_DIR="."
ARCH="arm"
TOOLCHAIN_PREFIX="arm-linux-gnueabi"
DRY_RUN=0
FIXES_APPLIED=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --src)        SRC_DIR="$2"; shift 2 ;;
        --arch)       ARCH="$2"; shift 2 ;;
        --toolchain)  TOOLCHAIN_PREFIX="$2"; shift 2 ;;
        --dry-run)    DRY_RUN=1; shift ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --src DIR           Source directory (default: current dir)"
            echo "  --arch ARCH         Target architecture (default: arm)"
            echo "  --toolchain PREFIX  Toolchain prefix (auto-detected)"
            echo "  --dry-run           Show what would be fixed without making changes"
            echo "  --help              Show this help"
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

case "$ARCH" in
    arm)     TOOLCHAIN_PREFIX="arm-linux-gnueabi" ;;
    armhf)   TOOLCHAIN_PREFIX="arm-linux-gnueabihf" ;;
    aarch64) TOOLCHAIN_PREFIX="aarch64-linux-gnu" ;;
    mips)    TOOLCHAIN_PREFIX="mips-linux-gnu" ;;
    mipsel)  TOOLCHAIN_PREFIX="mipsel-linux-gnu" ;;
    riscv64) TOOLCHAIN_PREFIX="riscv64-linux-gnu" ;;
esac

echo -e "${CYAN}${BOLD}Embedded Cross-Compile Doctor - Auto Fix${NC}  v${VERSION}"
echo -e "  Source: $SRC_DIR  Arch: $ARCH  Toolchain: $TOOLCHAIN_PREFIX"
[[ $DRY_RUN -eq 1 ]] && echo -e "  ${YELLOW}DRY RUN — no changes will be made${NC}"
echo ""

run_cmd() {
    if [[ $DRY_RUN -eq 1 ]]; then
        echo -e "  ${YELLOW}[DRY]${NC} $*"
    else
        echo -e "  ${GREEN}[FIX]${NC} $*"
        eval "$@"
    fi
    FIXES_APPLIED=$((FIXES_APPLIED+1))
}

# =============================================================================
# Fix 1: CRLF Line Endings
# =============================================================================
echo -e "${BOLD}Fix 1: Windows CRLF -> Unix LF${NC}"

if command -v dos2unix &>/dev/null; then
    crlf_files=$(find "$SRC_DIR" -maxdepth 5 -type f \( -name "*.sh" -o -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" -o -name "Makefile" -o -name "CMakeLists.txt" -o -name "*.pro" -o -name "*.pri" -o -name "*.py" -o -name "*.conf" -o -name "*.m4" -o -name "*.ac" -o -name "*.am" -o -name "*.cmake" -o -name "*.mk" \) -exec grep -Plc '\r' {} + 2>/dev/null || true)
    if [[ -n "$crlf_files" ]]; then
        count=$(echo "$crlf_files" | wc -l)
        echo "  Found $count files with CRLF"
        while IFS= read -r f; do
            run_cmd "dos2unix '$f'"
        done <<< "$crlf_files"
    else
        echo -e "  ${GREEN}No CRLF files found${NC}"
    fi
else
    echo -e "  ${YELLOW}dos2unix not installed. Install: sudo apt install dos2unix${NC}"
    echo "  Alternative: find $SRC_DIR -name '*.sh' -exec sed -i 's/\r$//' {} +"
fi

# =============================================================================
# Fix 2: Script Permissions
# =============================================================================
echo -e "\n${BOLD}Fix 2: Script Execute Permissions${NC}"

scripts=$(find "$SRC_DIR" -maxdepth 5 -type f -name "*.sh" ! -perm -u+x 2>/dev/null || true)
if [[ -n "$scripts" ]]; then
    count=$(echo "$scripts" | wc -l)
    echo "  Found $count scripts without execute permission"
    run_cmd "find '$SRC_DIR' -name '*.sh' -exec chmod +x {} +"
else
    echo -e "  ${GREEN}All scripts have execute permission${NC}"
fi

# =============================================================================
# Fix 3: CMake Toolchain File Generation
# =============================================================================
echo -e "\n${BOLD}Fix 3: CMake Toolchain File${NC}"

if [[ -f "$SRC_DIR/CMakeLists.txt" ]]; then
    toolchain_file=$(find "$SRC_DIR" -maxdepth 3 -name "*toolchain*.cmake" 2>/dev/null | head -1)
    if [[ -z "$toolchain_file" ]]; then
        toolchain_file="$SRC_DIR/toolchain-${ARCH}.cmake"
        echo "  Generating toolchain file: $toolchain_file"
        cat > /tmp/_toolchain_gen.cmake << TOOLCHAIN_EOF
# Auto-generated by embedded-cross-compile-doctor
# Target: ${ARCH} (${TOOLCHAIN_PREFIX})

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ${ARCH})

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_STRIP ${TOOLCHAIN_PREFIX}-strip)
set(CMAKE_AR ${TOOLCHAIN_PREFIX}-ar)
set(CMAKE_LINKER ${TOOLCHAIN_PREFIX}-ld)
set(CMAKE_RANLIB ${TOOLCHAIN_PREFIX}-ranlib)

set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Optional: Qt5 cross-compilation
# set(QT_QMAKE_EXECUTABLE /opt/qt5-arm/bin/qmake)
# set(CMAKE_PREFIX_PATH /opt/qt5-arm)
TOOLCHAIN_EOF
        run_cmd "cp /tmp/_toolchain_gen.cmake '$toolchain_file'"
        rm -f /tmp/_toolchain_gen.cmake
    else
        echo -e "  ${GREEN}Toolchain file already exists: $toolchain_file${NC}"
    fi
fi

# =============================================================================
# Fix 4: Qt OpenGL Flags
# =============================================================================
echo -e "\n${BOLD}Fix 4: Qt OpenGL Issues${NC}"

if [[ -d "$SRC_DIR" ]]; then
    pro_files=$(find "$SRC_DIR" -maxdepth 3 -name "*.pro" 2>/dev/null || true)
    if [[ -n "$pro_files" ]]; then
        while IFS= read -r pro; do
            if grep -qi "QT.*+=.*opengl\|QtOpenGL" "$pro" 2>/dev/null; then
                echo "  OpenGL reference found in $pro"
                if ! grep -q "no-opengl\|QT -= opengl" "$pro" 2>/dev/null; then
                    echo -e "  ${YELLOW}Manual fix needed: add 'QT -= opengl' to $pro or use -no-opengl in Qt configure${NC}"
                fi
            fi
        done <<< "$pro_files"
    fi
fi

# =============================================================================
# Fix 5: Clean Stale Build Artifacts
# =============================================================================
echo -e "\n${BOLD}Fix 5: Stale Build Artifacts${NC}"

if [[ -f "$SRC_DIR/config.status" && -f "$SRC_DIR/Makefile" ]]; then
    if grep -q "$(uname -m)" "$SRC_DIR/config.status" 2>/dev/null; then
        echo "  Detected host-arch artifacts from previous configure"
        echo -e "  ${YELLOW}Run 'make distclean' then reconfigure with --host=${TOOLCHAIN_PREFIX}${NC}"
    fi
fi

# Clean CMake cache if it references wrong compiler
if [[ -f "$SRC_DIR/CMakeCache.txt" ]]; then
    if grep -q "CMAKE_C_COMPILER.*$(uname -m)" "$SRC_DIR/CMakeCache.txt" 2>/dev/null; then
        echo "  CMake cache references host compiler"
        run_cmd "rm -f '$SRC_DIR/CMakeCache.txt' '$SRC_DIR/CMakeFiles'"
    fi
fi

# =============================================================================
# Fix 6: Generate Cross-Compile Wrapper Script
# =============================================================================
echo -e "\n${BOLD}Fix 6: Cross-Compile Convenience Wrapper${NC}"

wrapper="$SRC_DIR/build-arm.sh"
if [[ ! -f "$wrapper" ]]; then
    echo "  Generating build wrapper: $wrapper"

    if [[ -f "$SRC_DIR/CMakeLists.txt" ]]; then
        cat > /tmp/_build_wrapper.sh << WRAPPER_EOF
#!/usr/bin/env bash
# Auto-generated cross-compile build script
set -euo pipefail

BUILD_DIR="build-${ARCH}"
TOOLCHAIN_FILE="\$(dirname "\$0")/toolchain-${ARCH}.cmake"

mkdir -p "\$BUILD_DIR" && cd "\$BUILD_DIR"
cmake .. -DCMAKE_TOOLCHAIN_FILE="\$TOOLCHAIN_FILE" \\
         -DCMAKE_BUILD_TYPE=Release
make -j\$(nproc)
echo "Build complete: \$(pwd)"
WRAPPER_EOF
    elif [[ -f "$SRC_DIR/configure" || -f "$SRC_DIR/configure.ac" ]]; then
        cat > /tmp/_build_wrapper.sh << WRAPPER_EOF
#!/usr/bin/env bash
# Auto-generated cross-compile build script
set -euo pipefail

./configure --host=${TOOLCHAIN_PREFIX} \\
            --prefix=\$(pwd)/install-${ARCH} \\
            CFLAGS="-O2" CXXFLAGS="-O2"
make -j\$(nproc)
make install
echo "Build complete: \$(pwd)/install-${ARCH}"
WRAPPER_EOF
    fi

    if [[ -f /tmp/_build_wrapper.sh ]]; then
        run_cmd "cp /tmp/_build_wrapper.sh '$wrapper' && chmod +x '$wrapper'"
        rm -f /tmp/_build_wrapper.sh
    fi
else
    echo -e "  ${GREEN}Build wrapper already exists: $wrapper${NC}"
fi

# =============================================================================
# Summary
# =============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
if [[ $DRY_RUN -eq 1 ]]; then
    echo -e "${YELLOW}Dry run complete. $FIXES_APPLIED fixes would be applied.${NC}"
    echo -e "Run without --dry-run to apply fixes."
else
    echo -e "${GREEN}Done! $FIXES_APPLIED fixes applied.${NC}"
    echo -e "Run ${BOLD}./diagnose.sh${NC} again to verify."
fi
echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
